(()=>{'use strict';
const $=id=>document.getElementById(id);
const STRATEGY_LABELS={trend_swing:'趋势波段',breakout_pullback:'突破回踩',momentum_regime:'动量择时'};
let report=null,selectedStrategy='',signalFilter='全部';
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const finite=value=>value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value));
const num=(value,digits=2)=>finite(value)?Number(value).toLocaleString('zh-CN',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'—';
const compact=value=>finite(value)?Number(value).toLocaleString('zh-CN',{notation:'compact',maximumFractionDigits:1}):'—';
const money=value=>finite(value)?'¥'+Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const signedMoney=value=>finite(value)?(Number(value)>=0?'+':'-')+money(Math.abs(Number(value))):'—';
const pct=(value,digits=2)=>finite(value)?(Number(value)>=0?'+':'')+Number(value).toFixed(digits)+'%':'—';
const probability=value=>finite(value)?(Number(value)*100).toFixed(1)+'%':'—';
const ratio=(value,digits=2)=>finite(value)?Number(value).toFixed(digits):'—';
const date=value=>value?String(value).slice(0,10):'—';
const dateTime=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';
const tone=(value,invert=false)=>!finite(value)?'':((Number(value)>=0)!==invert?'up':'down');
const status=(text,kind='pending')=>'<span class="status '+kind+'">'+esc(text)+'</span>';
const metricCard=(label,value,note='',kind='')=>'<article class="metric"><div class="metric-label">'+esc(label)+'</div><div class="metric-value '+kind+'">'+esc(value)+'</div><div class="metric-note">'+esc(note)+'</div></article>';
const empty=text=>'<div class="empty">'+esc(text)+'</div>';
const strategyLabel=name=>STRATEGY_LABELS[name]||name||'未命名策略';
function table(headers,rows){if(!rows.length)return empty('暂无可展示数据');return '<table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>'}
function yLabel(value){const abs=Math.abs(value);if(abs>=10000)return compact(value);if(abs>=100)return num(value,0);return num(value,2)}

function renderLineChart(id,rows,key,{color='#6f91ff',fill=true,valueFormat=yLabel}={}){
  const host=$(id),points=(rows||[]).filter(row=>finite(row[key]));
  if(points.length<2){host.innerHTML='<div class="chart-empty">数据点不足，暂不能绘制</div>';return}
  const width=760,height=280,pad={l:58,r:18,t:18,b:40};let values=points.map(row=>Number(row[key])),min=Math.min(...values),max=Math.max(...values);
  if(min===max){const delta=Math.abs(min||1)*.1||1;min-=delta;max+=delta}
  const range=max-min,x=index=>pad.l+index*(width-pad.l-pad.r)/(points.length-1),y=value=>pad.t+(max-value)*(height-pad.t-pad.b)/range;
  const path=points.map((row,index)=>(index?'L':'M')+x(index).toFixed(2)+' '+y(Number(row[key])).toFixed(2)).join(' ');
  const area=path+' L '+x(points.length-1).toFixed(2)+' '+(height-pad.b)+' L '+pad.l+' '+(height-pad.b)+' Z';
  const grids=Array.from({length:5},(_,index)=>{const value=max-index*range/4,yy=y(value);return '<line class="chart-grid" x1="'+pad.l+'" x2="'+(width-pad.r)+'" y1="'+yy+'" y2="'+yy+'"/><text class="chart-axis" x="'+(pad.l-8)+'" y="'+(yy+3)+'" text-anchor="end">'+esc(valueFormat(value))+'</text>'}).join('');
  const markers=[0,Math.floor((points.length-1)/2),points.length-1].map(index=>'<text class="chart-axis" x="'+x(index)+'" y="'+(height-13)+'" text-anchor="middle">'+esc(date(points[index].time))+'</text>').join('');
  const dots=points.map((row,index)=>{if(points.length>80&&index%Math.ceil(points.length/40)!==0&&index!==points.length-1)return '';return '<circle cx="'+x(index)+'" cy="'+y(Number(row[key]))+'" r="2.5" fill="'+color+'"><title>'+esc(date(row.time)+' · '+valueFormat(row[key]))+'</title></circle>'}).join('');
  const gradient='gradient-'+id;
  host.innerHTML='<svg viewBox="0 0 '+width+' '+height+'" role="img"><defs><linearGradient id="'+gradient+'" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="'+color+'" stop-opacity=".52"/><stop offset="1" stop-color="'+color+'" stop-opacity="0"/></linearGradient></defs>'+grids+(fill?'<path d="'+area+'" fill="url(#'+gradient+')"/>':'')+'<path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="2.5" vector-effect="non-scaling-stroke"/>'+dots+markers+'</svg>';
}

function renderRiskReturnChart(strategies){
  const host=$('strategy-risk-chart');if(!strategies.length){host.innerHTML='<div class="chart-empty">暂无策略研究结果</div>';return}
  const width=760,height=280,p={l:58,r:25,t:24,b:43},xValues=strategies.map(row=>Math.abs(Number(row.optimized.max_drawdown_pct)||0)),yValues=strategies.map(row=>Number(row.optimized.total_return_pct)||0),xMax=Math.max(5,...xValues)*1.18,yMin=Math.min(0,...yValues),yMax=Math.max(1,...yValues)*1.12,yRange=yMax-yMin||1;
  const x=value=>p.l+value*(width-p.l-p.r)/xMax,y=value=>p.t+(yMax-value)*(height-p.t-p.b)/yRange;
  let grids='';for(let i=0;i<5;i++){const xv=xMax*i/4,yv=yMax-i*yRange/4,xx=x(xv),yy=y(yv);grids+='<line class="chart-grid" x1="'+xx+'" x2="'+xx+'" y1="'+p.t+'" y2="'+(height-p.b)+'"/><text class="chart-axis" x="'+xx+'" y="'+(height-15)+'" text-anchor="middle">'+num(xv,1)+'%</text><line class="chart-grid" x1="'+p.l+'" x2="'+(width-p.r)+'" y1="'+yy+'" y2="'+yy+'"/><text class="chart-axis" x="'+(p.l-8)+'" y="'+(yy+3)+'" text-anchor="end">'+num(yv,0)+'%</text>'}
  const colors=['#6f91ff','#8c6df2','#42c8e8','#f2bd55'];
  const dots=strategies.map((row,index)=>{const xx=x(Math.abs(Number(row.optimized.max_drawdown_pct)||0)),yy=y(Number(row.optimized.total_return_pct)||0),active=row.strategy===selectedStrategy;return '<circle cx="'+xx+'" cy="'+yy+'" r="'+(active?11:8)+'" fill="'+colors[index%colors.length]+'" opacity=".9"><title>'+esc(strategyLabel(row.strategy)+' · 收益 '+pct(row.optimized.total_return_pct)+' · 回撤 '+pct(row.optimized.max_drawdown_pct))+'</title></circle><text class="chart-label" x="'+(xx+13)+'" y="'+(yy+3)+'">'+esc(strategyLabel(row.strategy))+'</text>'}).join('');
  host.innerHTML='<svg viewBox="0 0 '+width+' '+height+'" role="img">'+grids+dots+'<text class="chart-note" x="'+(width/2)+'" y="'+(height-2)+'" text-anchor="middle">最大回撤绝对值（越左越好）</text></svg>';
}

function renderSourceMeta(data){const s=data.sources||{},ready=data.status==='ready';$('source-meta').innerHTML=[['报告状态',ready?'数据齐全':'部分数据',ready?'':'warn'],['回测/指标任务',s.research_run_id||'未找到',''],['训练数据任务',s.dataset_run_id||'未找到',''],['训练样本范围',date(s.dataset_start)+' → '+date(s.dataset_end),''],['行情快照',dateTime(s.pool_as_of),''],['模拟器',s.simulator_version||'未记录',''],['线上组合',s.ensemble_version?((s.ensemble_version)+' · '+(s.ensemble_component_count||0)+' 个组件'):'未记录','']].map(item=>'<span class="source-pill"><i class="dot '+item[2]+'"></i>'+esc(item[0]+'：'+item[1])+'</span>').join('')}
function renderAlerts(data){const alerts=data.verdict.alerts||[];$('alerts').innerHTML=alerts.map(item=>'<div class="alert '+esc(item.level||'info')+'"><strong>'+esc(item.title)+'</strong><span>'+esc(item.message)+'</span></div>').join('')}

function renderOverview(data){
  const best=data.strategies.find(row=>row.strategy===data.verdict.best_robust_strategy)||data.strategies[0]||{},summary=data.backtest.summary||{},selection=data.selection||{},portfolio=data.portfolio||{},gates=data.verdict.release_gate_passed_count||0;
  $('hero-metrics').innerHTML=[metricCard('近期基准收益',pct(summary.total_return_pct),'最近两个月，含交易成本',tone(summary.total_return_pct)),metricCard('稳健性最佳策略',strategyLabel(best.strategy),'按 CPCV 均值 Sharpe 排序','good'),metricCard('CPCV 均值 Sharpe',ratio((best.cpcv||{}).mean_test_sharpe),'组合清洗交叉验证'),metricCard('发布门槛',gates+'/'+(data.verdict.strategy_count||0)+' 通过','Optuna、CPCV、PBO、相对 Champion',gates===data.verdict.strategy_count?'good':'warn'),metricCard('当前可执行信号',String(selection.executable_count||0),'仅本地模拟订单'),metricCard('账户仓位',pct(portfolio.exposure_pct),'现金 '+money(portfolio.cash),portfolio.exposure_pct>80?'warn':'')].join('');
  const recent=Number(summary.total_return_pct)||0,cpcv=(best.cpcv||{}).mean_test_sharpe,optReturn=(best.optimized||{}).total_return_pct,champion=data.verdict.active_champion||{};
  const headline=recent>=0?'近期策略仍保持正收益':'长期研究强、近期环境适配偏弱';
  $('verdict-card').innerHTML='<div class="verdict-kicker">CURRENT RESEARCH VERDICT</div><h2>'+esc(headline)+'</h2><p>稳健性排序领先的是 <strong>'+esc(strategyLabel(best.strategy))+'</strong>，优化期收益 '+esc(pct(optReturn))+'、CPCV 均值 Sharpe '+esc(ratio(cpcv))+'。但最近两个月基准收益为 '+esc(pct(recent))+'，因此当前更适合用小仓验证，而不是直接按长期优化结果放大仓位。活动 Champion 为 '+esc(strategyLabel(champion.model_name||'未发布'))+'；信号中心采用三模型加权投票组合。</p><div class="verdict-tags">'+status((best.model||{}).live_published?'组合组件已发布':((best.model||{}).release_gate_passed?'发布门槛通过':'发布门槛未通过'),(best.model||{}).live_published|| (best.model||{}).release_gate_passed?'pass':'fail')+'<span class="tag">正收益折 '+esc(probability((best.cpcv||{}).positive_test_fold_ratio))+'</span><span class="tag">PBO '+esc(ratio((best.robustness||{}).pbo,3))+'</span><span class="tag">近期最大回撤 '+esc(pct(summary.max_drawdown_pct))+'</span></div>';
  const ml=data.models.training||{},llm=data.models.llm||{},dataset=data.dataset.quality||{};
  const dataQualityScopeOnly=dataset.status==='scope_only';
  const rows=[['传统逻辑与自动回测','3 套策略 + 费用/滑点/T+1 约束',data.strategies.length?'pass':'fail'],['Optuna + CPCV 发布门槛',gates+' 个 Challenger 通过',gates?'pass':'pending'],['机器学习概率',ml.status==='insufficient_data'?'样本不足，仅辅助排序':'候选评价可用',ml.status==='insufficient_data'?'pending':'pass'],['LLM 推理',llm.ready?'已连接 '+(llm.provider||''):'未就绪，本轮未参与决策',llm.ready?'pass':'pending'],['研究数据质量',dataQualityScopeOnly?'训练范围已核对（详细质量待对应研究产物）':dataset.status==='valid'?'通过，错误 '+(dataset.total_errors||0)+' 条':'存在异常',dataQualityScopeOnly?'pending':dataset.status==='valid'?'pass':'fail']];
  $('system-health').innerHTML=rows.map(row=>'<div class="health"><div><strong>'+esc(row[0])+'</strong><small>'+esc(row[1])+'</small></div>'+status(row[2]==='pass'?'可用':row[2]==='fail'?'异常':'待完善',row[2])+'</div>').join('')}

function renderPerformance(data){
  const b=data.backtest||{},s=b.summary||{},t=b.trade_metrics||{},window=b.window||{};
  $('performance-metrics').innerHTML=[metricCard('累计收益率',pct(s.total_return_pct),date(window.start)+' → '+date(window.end),tone(s.total_return_pct)),metricCard('年化收益率',pct(s.annualized_return_pct),'由近期窗口折算',tone(s.annualized_return_pct)),metricCard('夏普比率',ratio(s.sharpe_ratio),'收益/总波动'),metricCard('最大回撤',pct(s.max_drawdown_pct),'越接近 0 越好','down'),metricCard('胜率',pct(s.win_rate),'已完成交易'),metricCard('盈亏因子',ratio(t.profit_factor),'总盈利/总亏损'),metricCard('单笔期望',signedMoney(t.expectancy),'每笔已完成交易',tone(t.expectancy)),metricCard('平均盈利',signedMoney(t.average_win),'盈利交易均值','up'),metricCard('平均亏损',signedMoney(t.average_loss),'亏损交易均值','down'),metricCard('盈亏比',ratio(t.payoff_ratio),'平均盈利/平均亏损'),metricCard('完成交易',String(s.completed_trade_count??t.completed_trade_count??0),'卖出闭环'),metricCard('最大连亏',String(t.max_consecutive_losses??0)+' 笔','连续亏损交易')].join('');
  renderLineChart('equity-chart',b.equity_curve||[],'value',{color:'#6f91ff',valueFormat:value=>money(value)});renderLineChart('drawdown-chart',b.equity_curve||[],'drawdown_pct',{color:'#35d2a1',fill:true,valueFormat:value=>pct(value)})}

function renderStrategyTabs(strategies){$('strategy-tabs').innerHTML=strategies.map(row=>'<button data-strategy="'+esc(row.strategy)+'" class="'+(row.strategy===selectedStrategy?'active':'')+'">'+esc(strategyLabel(row.strategy))+'</button>').join('')}
function renderStrategyProfile(strategies){const row=strategies.find(item=>item.strategy===selectedStrategy)||strategies[0];if(!row){$('strategy-profile').innerHTML=empty('暂无策略结果');return}const base=row.baseline||{},opt=row.optimized||{},cpcv=row.cpcv||{},rob=row.robustness||{},wfo=row.walk_forward||{},params=row.best_params||{},model=row.model||{},gate=model.release_gate_passed;
  const delta=finite(opt.sharpe_ratio)&&finite(base.sharpe_ratio)?Number(opt.sharpe_ratio)-Number(base.sharpe_ratio):null,wfoWeak=finite(wfo.total_return_pct)&&Number(wfo.total_return_pct)<=0&&Number(opt.total_return_pct)>0;
  const gateText=model.live_published?'组合组件已发布':(gate?'可申请发布':'门槛未通过'),gateKind=(model.live_published||gate)?'pass':'fail';$('strategy-profile').innerHTML='<div class="profile-title"><h3>'+esc(strategyLabel(row.strategy))+'</h3>'+status(gateText,gateKind)+'</div><div class="profile-grid"><div class="profile-stat"><span>优化 Sharpe</span><strong>'+esc(ratio(opt.sharpe_ratio))+'</strong></div><div class="profile-stat"><span>Sharpe 增益</span><strong class="'+tone(delta)+'">'+esc(finite(delta)?(delta>=0?'+':'')+ratio(delta):'—')+'</strong></div><div class="profile-stat"><span>CPCV Sharpe</span><strong>'+esc(ratio(cpcv.mean_test_sharpe))+'</strong></div><div class="profile-stat"><span>正收益折</span><strong>'+esc(probability(cpcv.positive_test_fold_ratio))+'</strong></div><div class="profile-stat"><span>PBO</span><strong>'+esc(ratio(rob.pbo,3))+'</strong></div><div class="profile-stat"><span>Walk-Forward</span><strong class="'+tone(wfo.total_return_pct)+'">'+esc(pct(wfo.total_return_pct))+'</strong></div></div><div><div class="metric-label" style="margin-bottom:6px">Optuna 最优参数</div><div class="params">'+Object.entries(params).map(([key,value])=>'<span class="param">'+esc(key)+' = '+esc(value)+'</span>').join('')+'</div></div><div class="insight">'+esc(model.live_published?'该策略已作为当前三模型组合组件发布；本页门槛状态表示其发布审计结果，不再按 Challenger 重新判定。':(wfoWeak?'完整样本和 CPCV 表现较强，但滚动 Walk-Forward 未同步转正。发布后仍应以小仓纸面运行观察参数漂移。':'优化结果、CPCV 与滚动窗口方向较一致，可继续进入纸面 Champion/Challenger 观察。'))+'</div>'}
function renderStrategyTable(strategies){const rows=strategies.map(row=>{const opt=row.optimized||{},base=row.baseline||{},c=row.cpcv||{},r=row.robustness||{},w=row.walk_forward||{},m=row.model||{},gate=m.release_gate_passed,label=m.live_published?'已发布组件':(gate?'通过':'未通过');return '<tr class="strategy-row '+(row.strategy===selectedStrategy?'selected':'')+'" data-strategy="'+esc(row.strategy)+'"><td><strong>'+esc(strategyLabel(row.strategy))+'</strong></td><td>'+pct(base.total_return_pct)+'</td><td class="'+tone(opt.total_return_pct)+'">'+pct(opt.total_return_pct)+'</td><td>'+ratio(opt.sharpe_ratio)+'</td><td class="down">'+pct(opt.max_drawdown_pct)+'</td><td>'+pct(opt.win_rate)+'</td><td>'+ratio(c.mean_test_sharpe)+'</td><td>'+probability(c.positive_test_fold_ratio)+'</td><td>'+ratio(r.pbo,3)+'</td><td>'+probability(m.max_peer_trade_overlap)+'</td><td class="'+tone(w.total_return_pct)+'">'+pct(w.total_return_pct)+'</td><td>'+((row.optimization||{}).completed_trials||0)+'</td><td>'+status(label,(m.live_published||gate)?'pass':'fail')+'</td></tr>'});$('strategy-table').innerHTML=table(['策略','原始收益','优化收益','优化 Sharpe','最大回撤','胜率','CPCV Sharpe','正收益折','PBO','最高交易重合','Walk-Forward','完成 Trial','发布状态'],rows)}
function renderStrategies(data){const strategies=data.strategies||[];if(!selectedStrategy)selectedStrategy=data.verdict.best_robust_strategy||(strategies[0]||{}).strategy||'';renderStrategyTabs(strategies);renderRiskReturnChart(strategies);renderStrategyProfile(strategies);renderStrategyTable(strategies)}

function renderValidation(data){const strategies=data.strategies||[];$('model-cards').innerHTML=strategies.length?strategies.map(row=>{const opt=row.optimized||{},c=row.cpcv||{},r=row.robustness||{},model=row.model||{},gate=model.release_gate_passed,label=model.live_published?'组合组件已发布':(gate?'门槛通过':'门槛未通过');return '<article class="model-card"><div style="display:flex;justify-content:space-between;gap:8px"><h4>'+esc(strategyLabel(row.strategy))+'</h4>'+status(label,(model.live_published||gate)?'pass':'fail')+'</div><div class="model-id">'+esc(model.model_id||'尚未注册')+'</div><div class="model-stats"><div class="model-stat"><span>Sharpe</span><strong>'+ratio(opt.sharpe_ratio)+'</strong></div><div class="model-stat"><span>CPCV</span><strong>'+ratio(c.mean_test_sharpe)+'</strong></div><div class="model-stat"><span>PBO</span><strong>'+ratio(r.pbo,3)+'</strong></div><div class="model-stat"><span>交易重合</span><strong>'+probability(model.max_peer_trade_overlap)+'</strong></div><div class="model-stat"><span>完成 Trial</span><strong>'+((row.optimization||{}).completed_trials||0)+'</strong></div></div></article>'}).join(''):empty('尚未生成 Challenger');
  const models=data.models||{},performance=models.performance||{},training=models.training||{},candidate=models.candidate_training||{},replay=models.historical_replay||{},one=performance.next_trading_day||{},five=performance.next_5_trading_days||{},candidateOne=((candidate.models||{}).next_trading_day||{}),candidateFive=((candidate.models||{}).next_5_trading_days||{}),candidateModels=candidateOne.models||{},fiveCandidateModels=candidateFive.models||{},challenger=candidateOne.best_candidate||Object.values(candidateModels).filter(item=>item&&item.status==='candidate'&&finite(item.brier_score)).sort((a,b)=>Number(a.brier_score)-Number(b.brier_score))[0]||{},fiveChallenger=candidateFive.best_candidate||Object.values(fiveCandidateModels).filter(item=>item&&item.status==='candidate'&&finite(item.brier_score)).sort((a,b)=>Number(a.brier_score)-Number(b.brier_score))[0]||{};
  const methodName=challenger.calibration_method==='platt_sigmoid'?'Logistic 回归 + Platt 概率校准':challenger.model_name==='hist_gradient_boosting'?'直方图梯度提升分类':challenger.model_name==='logistic'?'Logistic 回归':'传统概率基线与候选分类模型';
  $('ml-method-title').textContent=methodName;
  const metricValue=(value,threshold,operator)=>finite(value)?ratio(value,4)+'（门槛'+operator+ratio(threshold,3)+'）':'暂无数据';
  const traditionalReady=finite(one.auc)&&Number(one.auc)>=.55&&finite(one.brier_score)&&Number(one.brier_score)<=.25,candidateReady=finite(challenger.auc)&&Number(challenger.auc)>=.55&&finite(challenger.brier_score)&&Number(challenger.brier_score)<=.25,fiveCandidateReady=finite(fiveChallenger.auc)&&Number(fiveChallenger.auc)>=.55&&finite(fiveChallenger.brier_score)&&Number(fiveChallenger.brier_score)<=.25,rawStatus=traditionalReady?'pass':(candidateReady?'baseline':'fail');
  const mlRows=[['候选训练状态',training.status==='insufficient_data'?'样本不足':'可评估',training.status==='insufficient_data'?'pending':'pass',training.status==='insufficient_data'?'样本不足':'可评估'],['原始概率基线 AUC',metricValue(one.auc,.55,'≥'),rawStatus,traditionalReady?'达标':candidateReady?'仅对照':'未达标'],['原始概率基线 Brier',metricValue(one.brier_score,.25,'≤'),rawStatus,traditionalReady?'达标':candidateReady?'仅对照':'未达标'],['候选测试样本',String(challenger.test_count??0),Number(challenger.test_count||0)>=30?'pass':'pending',Number(challenger.test_count||0)>=30?'充足':'不足'],['最佳候选 AUC',metricValue(challenger.auc,.55,'≥'),finite(challenger.auc)&&Number(challenger.auc)>=.55?'pass':'fail',finite(challenger.auc)&&Number(challenger.auc)>=.55?'达标':'未达标'],['最佳候选 Brier',metricValue(challenger.brier_score,.25,'≤'),finite(challenger.brier_score)&&Number(challenger.brier_score)<=.25?'pass':'fail',finite(challenger.brier_score)&&Number(challenger.brier_score)<=.25?'达标':'未达标'],['5日最佳候选',finite(fiveChallenger.auc)&&finite(fiveChallenger.brier_score)?'AUC '+ratio(fiveChallenger.auc,4)+' / Brier '+ratio(fiveChallenger.brier_score,4):'暂无数据',fiveCandidateReady?'pass':'fail',fiveCandidateReady?'达标':'未达标']];
  const mlInsight='样本量已足够评估。三种策略模型负责短线趋势、突破回踩和动量择时信号，并在组合层加权投票；Logistic 只负责估计未来1/5日上涨概率，作为波段综合分的辅助证据，不单独选股、不替换三模型，也不改变三模型发布门槛。'+(traditionalReady?' 原始概率基线达到当前门槛。':candidateReady?' 原始概率基线在近期市场状态下失效，已降级为审计对照。':' 原始概率基线区分度和校准均未达标。')+(candidateReady?' 增强特征 + Platt 保守校准候选已同时通过次日 AUC 与 Brier 门槛，可进入纸面验证。':' 次日候选尚未同时通过 AUC 与 Brier 门槛。')+(fiveCandidateReady?' 5 日候选也已达标。':' 5 日候选仍未达标，不应因次日模型改善而自动放行。')+' 训练采用按日期分组的清洗留出窗口；候选模型不会自动替换线上模型。';
  $('ml-health').innerHTML='<div class="health-list">'+mlRows.map(row=>'<div class="health"><div><strong>'+esc(row[0])+'</strong><small>'+esc(row[1])+'</small></div>'+status(row[3],row[2])+'</div>').join('')+'</div><div class="insight" style="margin-top:10px">'+esc(mlInsight)+'</div>';
  const llm=(data.models||{}).llm||{},missing=Array.isArray(llm.missing)?llm.missing.join('、'):'';
  $('llm-health').innerHTML='<div class="health-list"><div class="health"><div><strong>服务状态</strong><small>'+(llm.ready?'可调用并可参与融合':'未就绪，本轮报告不把 LLM 视为有效证据')+'</small></div>'+status(llm.ready?'已连接':'未连接',llm.ready?'pass':'pending')+'</div><div class="health"><div><strong>Provider / 模型</strong><small>'+esc((llm.provider||'—')+' / '+(llm.model||'—'))+'</small></div>'+status(llm.enabled?'已配置':'未启用',llm.enabled?'pass':'pending')+'</div><div class="health"><div><strong>知识库版本</strong><small>'+esc(llm.knowledge_version||'未记录')+'</small></div>'+status(llm.knowledge_version?'已加载':'缺失',llm.knowledge_version?'pass':'pending')+'</div><div class="health"><div><strong>缺失配置</strong><small>'+esc(missing||'无')+'</small></div>'+status(missing?'待补齐':'完整',missing?'pending':'pass')+'</div></div>'}

function actionClass(action){return action.includes('买')?'action-buy':action.includes('卖')?'action-sell':'action-hold'}
function filteredSignals(){const signals=(report.selection||{}).signals||[];return signalFilter==='全部'?signals:signals.filter(item=>item.action===signalFilter)}
function renderSignalChart(){const rows=filteredSignals().slice().sort((a,b)=>Number(b.swing_score??b.selection_score)-Number(a.swing_score??a.selection_score)).slice(0,10);$('signal-chart').innerHTML=rows.length?'<div class="signal-bars">'+rows.map(item=>{const score=item.swing_score??item.selection_score;return '<div class="signal-bar"><div class="signal-name" title="'+esc(item.name+' '+item.symbol)+'">'+esc(item.name)+' <span class="'+actionClass(item.action)+'">'+esc(item.action)+'</span></div><div class="bar-track"><div class="bar-fill" style="width:'+Math.max(0,Math.min(100,Number(score)||0))+'%"></div></div><div class="bar-value">'+num(score,1)+' / '+probability(item.up_probability_1d)+' / '+probability(item.up_probability_5d)+'</div></div>'}).join('')+'</div>':empty('当前筛选条件下没有信号')}
function renderSectorStrength(data){const rows=(data.selection||{}).sector_strength||[];$('sector-strength').innerHTML=rows.length?'<div class="signal-bars">'+rows.slice(0,10).map(item=>'<div class="signal-bar"><div class="signal-name">'+esc(item.sector)+' <small style="color:var(--muted)">'+item.buy_candidates+' 候选</small></div><div class="bar-track"><div class="bar-fill" style="width:'+Math.max(0,Math.min(100,Number(item.average_score)||0))+'%"></div></div><div class="bar-value">'+num(item.average_score,1)+'</div></div>').join('')+'</div>':empty('暂无板块聚合数据')}
function renderSignalTable(){const rows=filteredSignals().map(item=>'<tr title="'+esc(item.reason)+'"><td>'+esc(item.selection_rank||'—')+'</td><td><strong>'+esc(item.name)+'</strong><br><span style="color:var(--muted)">'+esc(item.symbol)+'</span></td><td>'+esc(item.sector)+'</td><td class="'+actionClass(item.action)+'">'+esc(item.action)+'</td><td><span class="score">'+num(item.swing_score??item.selection_score,1)+'</span><br><span style="color:var(--muted)">技术 '+num(item.selection_score,1)+'</span></td><td>'+probability(item.up_probability_1d)+'</td><td>'+probability(item.up_probability_5d)+'</td><td>'+probability(item.validation_accuracy)+'</td><td>'+esc(item.trend_direction||item.trend||'—')+'</td><td>'+num(item.mfi14,1)+'<br>'+status(item.mfi_filter_passed?'通过':'等待',item.mfi_filter_passed?'pass':'pending')+'</td><td>'+money(item.current_price)+'</td><td>'+money(item.suggested_price)+'</td><td>'+money(item.stop_price)+'</td><td>'+money(item.take_profit_price)+'</td><td>'+ratio(item.risk_reward_ratio)+'</td><td>'+status(item.execution_ready?'可执行':'仅观察',item.execution_ready?'pass':'pending')+'</td></tr>');$('signal-table').innerHTML=table(['排名','标的','板块','动作','波段综合分','1日上涨概率','5日上涨概率','验证准确率','趋势','MFI14','现价','建议价','止损','止盈','风险收益比','订单状态'],rows)}
function renderSelection(data){const counts=(data.selection||{}).action_counts||{},actions=['全部',...Object.keys(counts).sort((a,b)=>(counts[b]||0)-(counts[a]||0))];if(!actions.includes(signalFilter))signalFilter='全部';$('signal-filters').innerHTML=actions.map(action=>'<button data-filter="'+esc(action)+'" class="'+(action===signalFilter?'active':'')+'">'+esc(action)+' '+(action==='全部'?((data.selection||{}).signals||[]).length:counts[action])+'</button>').join('');renderSignalChart();renderSectorStrength(data);renderSignalTable()}

function renderPortfolio(data){const p=data.portfolio||{};$('portfolio-metrics').innerHTML=[metricCard('账户权益',money(p.equity),'现金 + 当前市值'),metricCard('可用现金',money(p.cash),'本地纸面账户'),metricCard('持仓市值',money(p.market_value),'按最新缓存行情'),metricCard('仓位比例',pct(p.exposure_pct),'风险预算',p.exposure_pct>80?'warn':''),metricCard('未实现盈亏',signedMoney(p.unrealized_pnl),'当前持仓',tone(p.unrealized_pnl)),metricCard('持仓标的',String((p.positions||[]).length),'手工交易 '+(p.manual_trade_count||0)+' 笔')].join('');
  const positions=p.positions||[],equity=Number(p.equity)||1,allocation=[...positions.map(item=>({label:item.name,value:item.market_value,weight:Number(item.market_value)/equity*100})),{label:'现金',value:p.cash,weight:Number(p.cash)/equity*100}].sort((a,b)=>b.weight-a.weight);$('allocation').innerHTML=allocation.length?allocation.map(item=>'<div class="allocation-row"><div class="allocation-label">'+esc(item.label)+'</div><div class="allocation-track"><div class="allocation-fill" style="width:'+Math.max(0,Math.min(100,item.weight))+'%"></div></div><div class="allocation-value">'+pct(item.weight)+' · '+money(item.value)+'</div></div>').join(''):empty('暂无账户分配数据');
  $('position-table').innerHTML=table(['标的','板块','数量','成本','现价','市值','未实现盈亏','当日涨跌'],positions.map(item=>'<tr><td><strong>'+esc(item.name)+'</strong><br><span style="color:var(--muted)">'+esc(item.symbol)+'</span></td><td>'+esc(item.sector)+'</td><td>'+num(item.quantity,0)+'</td><td>'+money(item.entry_price)+'</td><td>'+money(item.current_price)+'</td><td>'+money(item.market_value)+'</td><td class="'+tone(item.unrealized_pnl)+'">'+signedMoney(item.unrealized_pnl)+'</td><td class="'+tone(item.change_pct)+'">'+pct(item.change_pct)+'</td></tr>'));
  const trades=(data.backtest.trades||[]).slice().reverse();$('trade-table').innerHTML=table(['时间','标的','动作','价格','数量','净盈亏','原因'],trades.map(item=>'<tr><td>'+esc(date(item.time))+'</td><td>'+esc(item.name||'历史标的')+'</td><td class="'+actionClass(item.action==='buy'?'买入':'卖出')+'">'+esc(item.action==='buy'?'买入':'卖出')+'</td><td>'+money(item.price)+'</td><td>'+num(item.quantity,0)+'</td><td class="'+tone(item.net_pnl)+'">'+signedMoney(item.net_pnl)+'</td><td title="'+esc(item.reason)+'">'+esc((item.reason||'—').slice(0,38))+'</td></tr>'))}

function renderDataQuality(data){const d=data.dataset||{},s=d.snapshot||{},q=d.quality||{},src=data.sources||{},scopeOnly=q.status==='scope_only',qualityLabel=scopeOnly?'范围已核对':(q.status==='valid'?'通过':'异常'),qualityNote=scopeOnly?'训练范围记录；未在本运行重复扫描字段质量':'错误 '+(q.total_errors||0)+' / 警告 '+(q.total_warnings||0);$('data-metrics').innerHTML=[metricCard('数据质量',qualityLabel,qualityNote,scopeOnly?'':(q.status==='valid'?'good':'bad')),metricCard('数据版本',s.version||src.dataset_version||'—',scopeOnly?'训练范围来源':'SHA 快照版本'),metricCard('样本范围',date(s.start)+' → '+date(s.end),'最近完整行情日'),metricCard('股票数量',String(q.symbol_count??(s.symbols||[]).length??0),'当前研究池'),metricCard('数据行数',compact(s.row_count),'OHLCV 记录'),metricCard('特征 / 标签',d.feature_count+' / '+d.label_count,(d.feature_version||'')+' · '+(d.label_version||''))].join('');
  const leakage=(q.future_leakage_check||{}).status==='passed';$('methodology').innerHTML=[['近期基准回测','当前持仓与观察池，最近约 60 个自然日；收盘信号、10% 单票仓位、最多 5 只、100 股整手，并计入手续费、印花税与滑点。'],['策略优化与稳健性','Optuna TPE 负责参数搜索；CPCV 负责组合清洗交叉验证；PBO 衡量过拟合风险；Walk-Forward 用滚动窗口检查参数漂移。'],['波段综合分口径','基础权重为技术选择分45%、次日概率20%、5日概率35%；概率权重还会按各自样本外 AUC、Brier 或准确率自动折减，缺失项剔除后重新归一化。趋势与 MFI 仍是交易门槛。'],['算法边界','发布门槛仅证明研究审计条件已满足。机器学习样本不足或 LLM 未就绪时，报告会明确降级，不把缺失能力伪装为已融合。'],['防未来函数',leakage?'特征只使用 t 及以前数据，标签严格使用未来窗口；当前检查已通过。':'当前未取得通过记录，请谨慎解释结果。'],['数据来源','聚合接口 /api/reports/backtest-dashboard；源数据来自本地状态、行情缓存、研究任务、模型注册表和评价数据库。']].map(item=>'<article class="method"><strong>'+esc(item[0])+'</strong><p>'+esc(item[1])+'</p></article>').join('')}

function render(data){report=data;renderSourceMeta(data);renderAlerts(data);renderOverview(data);renderPerformance(data);renderStrategies(data);renderValidation(data);renderSelection(data);renderPortfolio(data);renderDataQuality(data);$('updated').textContent='报告更新时间：'+dateTime(data.generated_at)+' · 指标任务：'+(data.sources.research_run_id||'未找到')+' · 训练数据：'+(data.sources.dataset_run_id||'未找到')}
async function load(){const main=$('main'),button=$('refresh');main.classList.add('loading');button.disabled=true;try{const response=await fetch('../api/reports/backtest-dashboard',{cache:'no-store'});let body={};try{body=await response.json()}catch(_){throw Error('服务返回的不是有效 JSON')}if(!response.ok)throw Error(body.error||('HTTP '+response.status));render(body)}catch(error){$('alerts').innerHTML='<div class="error">报告加载失败：'+esc(error.message)+'</div>';console.error(error)}finally{main.classList.remove('loading');button.disabled=false}}
document.addEventListener('click',event=>{const strategy=event.target.closest('[data-strategy]');if(strategy&&report){selectedStrategy=strategy.dataset.strategy;renderStrategies(report);return}const filter=event.target.closest('[data-filter]');if(filter&&report){signalFilter=filter.dataset.filter;renderSelection(report)}});
$('refresh').addEventListener('click',load);$('print').addEventListener('click',()=>window.print());
const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;document.querySelectorAll('.nav a').forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+visible.target.id))},{rootMargin:'-20% 0px -65% 0px',threshold:[0,.2,.6]});document.querySelectorAll('.section').forEach(section=>observer.observe(section));
load();
})();
