"""Structured schemas shared by LLM analysis, fusion, and persistence."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

AssessmentStatus = Literal[
    "valid_directional",
    "valid_neutral",
    "insufficient_data",
    "unavailable",
    "degraded",
]
TradeAction = Literal[
    "观察",
    "等待买入",
    "买入",
    "加仓",
    "持有",
    "减仓",
    "卖出",
    "止损",
    "清仓",
]


class _SchemaModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Evidence(_SchemaModel):
    type: Literal["support", "counter", "risk"]
    reference: str
    summary: str


class HorizonProbabilities(_SchemaModel):
    next_trading_day: float | None = Field(default=None, ge=0.0, le=1.0)
    next_5_trading_days: float | None = Field(default=None, ge=0.0, le=1.0)


class RiskAssessment(_SchemaModel):
    """Top-level, machine-readable risk state shared by LLM and fusion output."""

    risk_status: Literal["valid", "unknown", "unavailable"] = "unknown"
    risk_level: Literal["low", "medium", "high", "critical", "unknown"] = "unknown"
    risk_factors: list[str] = Field(default_factory=list)
    invalidation_conditions: list[str] = Field(default_factory=list)
    stop_loss_enabled: bool = False
    stop_loss_price: float | None = None
    stop_loss_exit_ratio: float = Field(default=1.0, ge=0.0, le=1.0)
    clear_enabled: bool = False
    clear_exit_ratio: float = Field(default=1.0, ge=0.0, le=1.0)
    human_review_required: bool = False


class NextDayScenario(_SchemaModel):
    """Actionable next-session playbook, not a guaranteed forecast."""

    base_case: str = ""
    bullish_case: str = ""
    bearish_case: str = ""
    confirmation_signals: list[str] = Field(default_factory=list)
    invalidation_signals: list[str] = Field(default_factory=list)
    open_plan: str = ""
    hold_plan: str = ""
    exit_plan: str = ""


class LLMTradeAnalysis(_SchemaModel):
    assessment_status: AssessmentStatus
    unavailable_reason: str | None = None
    score: float | None = Field(default=None, ge=0.0, le=100.0)
    subjective_up_probabilities: HorizonProbabilities
    confidence: float = Field(ge=0.0, le=1.0)
    trend_direction: str
    market_regime: str
    market_effect: Literal["顺风", "中性", "逆风", "未知"]
    sector_strength: str
    sector_effect: Literal["顺风", "中性", "逆风", "未知"]
    stance: str
    suggested_action: TradeAction | None
    operation_advice: str
    # Concise, user-facing rationale generated by the model. This is a
    # summary of facts, risks, and conditional actions—not hidden reasoning.
    model_output: str | None = None
    facts_used: list[str]
    evidence: list[Evidence]
    counter_evidence: list[Evidence]
    inferences: list[str]
    knowledge_refs: list[str]
    invalidation_conditions: list[str]
    missing_information: list[str]
    requires_human_review: bool
    risk: RiskAssessment = Field(default_factory=RiskAssessment)
    next_day_scenario: NextDayScenario = Field(default_factory=NextDayScenario)

    @classmethod
    def unavailable(cls, reason: str) -> "LLMTradeAnalysis":
        return cls(
            assessment_status="unavailable",
            unavailable_reason=reason,
            score=None,
            subjective_up_probabilities={
                "next_trading_day": None,
                "next_5_trading_days": None,
            },
            confidence=0.0,
            trend_direction="未知",
            market_regime="未知",
            market_effect="未知",
            sector_strength="未知",
            sector_effect="未知",
            stance="模型不可用",
            suggested_action=None,
            operation_advice="LLM 不可用，采用传统基线。",
            model_output=None,
            facts_used=[],
            evidence=[],
            counter_evidence=[],
            inferences=[],
            knowledge_refs=[],
            invalidation_conditions=[],
            missing_information=[],
            requires_human_review=True,
            risk=RiskAssessment(
                risk_status="unavailable",
                risk_level="unknown",
                risk_factors=[reason],
                human_review_required=True,
            ),
        )


class ProviderUsage(_SchemaModel):
    input_tokens: int | None = None
    output_tokens: int | None = None
    cached_tokens: int | None = None


class ProviderResult(_SchemaModel):
    analysis: LLMTradeAnalysis
    usage: ProviderUsage = Field(default_factory=ProviderUsage)
    response_id: str | None = None
    raw_text: str
    latency_ms: int
